-- ===================================================
-- 1. CLEANUP: Destroy old tables to remove "Ghost Files"
-- ===================================================
-- We drop the publication first to avoid dependency errors
drop publication if exists supabase_realtime; 
drop table if exists file_locks;
drop table if exists system_status;

-- ===================================================
-- 2. CREATE MASTER SWITCH (Legacy/Global Lock)
-- ===================================================
create table system_status (
  id bigint primary key,
  is_locked boolean default false,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Initialize the switch (Unlocked by default)
insert into system_status (id, is_locked) values (1, false);

-- Enable Security (Allow everyone to read/write for this demo)
alter table system_status enable row level security;
create policy "Allow all access" on system_status for all using (true) with check (true);

-- ===================================================
-- 3. CREATE FILE LOCKS (The Core Table)
-- ===================================================
create table file_locks (
  id bigint generated by default as identity primary key,
  filename text unique not null,
  is_locked boolean default false,
  last_accessed timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Security
alter table file_locks enable row level security;
create policy "Allow all access" on file_locks for all using (true) with check (true);

-- ===================================================
-- 4. ENABLE REALTIME (Critical for Frontend Sync)
-- ===================================================
-- Create a new publication that listens to BOTH tables
create publication supabase_realtime for table system_status, file_locks;

-- Optimization: Ensure the frontend receives the full row data on update
alter table file_locks replica identity full;
