-- 1. Reset: Clear old data to prevent conflicts
drop table if exists file_locks;

-- 2. Create the Advanced File Table
create table file_locks (
  id bigint generated by default as identity primary key,
  file_path text unique not null,  -- Stores "folder/subfolder/file.txt"
  is_directory boolean default false, -- TRUE if it's a folder
  is_locked boolean default false,
  last_accessed timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Enable Security & Realtime
alter table file_locks enable row level security;
create policy "Allow all access" on file_locks for all using (true) with check (true);

drop publication if exists supabase_realtime;
create publication supabase_realtime for table system_status, file_locks;
alter table file_locks replica identity full;
